#!/usr/bin/python

import os
import sys
import string
import subprocess

args=sys.argv[1:]

if (args[0]=="-s"):
  use_sed=True
  args.pop(0)
else:
  use_sed=False

cmdstr="paste "

while len(args)>0:
  # expects a file name
  fname=args[0]
  args.pop(0)

  if not( os.path.isfile(fname) ):
    print fname+" is not a real file."
    os._exit(0)
  
  # expects a list of columns
  cols=[]
  while (len(args)>0 and args[0].isdigit() and int(args[0])>0):
    cols.extend(["$"+args[0]])
    args.pop(0)

  if len(cols)==0:
    print "No columns selected for "+fname
    os.exit(0)
  
  cmdstr+="<( awk '{print "+'"\\t"'.join(cols)+"}' "+fname+" ) "


if use_sed:
  cmdstr+="| sed '1d'"

subprocess.call(['bash', '-c', cmdstr ])
